# Generated by Django 2.1.2 on 2018-11-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentInput', '0007_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_credits',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='course_weight',
            field=models.IntegerField(default=1),
        ),
    ]
