# Generated by Django 2.1.2 on 2018-11-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentInput', '0011_auto_20181108_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=7),
        ),
    ]
