# Generated by Django 2.1.2 on 2018-11-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentInput', '0012_auto_20181108_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
