# Generated by Django 2.1.2 on 2018-11-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentInput', '0013_auto_20181112_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_course_request', models.ManyToManyField(to='studentInput.Course')),
            ],
        ),
    ]
