# Generated by Django 2.1.2 on 2019-01-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentInput', '0014_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_tj_description',
            field=models.CharField(default='blakn tj description', max_length=1000),
            preserve_default=False,
        ),
    ]
