# Generated by Django 2.1.2 on 2019-01-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentInput', '0015_course_course_tj_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_tj_description',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.CharField(max_length=10000),
        ),
    ]
