# Generated by Django 2.1.2 on 2019-01-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentInput', '0017_auto_20190115_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_first_name',
            field=models.CharField(default='Young', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_last_name',
            field=models.CharField(default='Qi', max_length=50),
            preserve_default=False,
        ),
    ]
