# Generated by Django 2.1.2 on 2019-02-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentInput', '0019_auto_20190219_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='teacher',
        ),
        migrations.AddField(
            model_name='section',
            name='teachers',
            field=models.ManyToManyField(to='studentInput.Teacher'),
        ),
    ]
