# Generated by Django 2.1.2 on 2019-03-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentInput', '0021_auto_20190314_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_id',
        ),
    ]
