# Generated by Django 2.1.2 on 2019-03-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentInput', '0022_remove_section_section_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_id',
            field=models.CharField(default='delete', max_length=20),
            preserve_default=False,
        ),
    ]
